package:
  name: randompartitions
  version: 0.1

source:
  git_url: https://github.com/alicedb2/randompartitions.git

build:
  noarch: generic

requirements:
  build:
    - python
    - setuptools

  run:
    - python

tests:
  imports:
    - randompartitions
